shakawi/urls.py
from django.urls import path
from . import views


app_name="shakawi"


urlpatterns = [
    path('', views.home, name='login_page'),
    path('main',views.shakawi_user , name='main'),
    path('logout', views.home, name='logout'),
    path('new_shab_fit/<int:page_id>', views.new_shab, name='new_shab_fit'),
    path('new_shab_ability/<int:page_id>', views.new_shab, name='new_shab_ability'),
    path('new_shab_ten_percent/<int:page_id>', views.new_shab, name='new_shab_ten'),
    path('new_shab_unfit/<int:page_id>', views.new_shab, name='new_shab_unfit'),
    path('search_single', views.search_single, name='search_single'),
    path('search_reports', views.print_reports, name='search_reports'),
    path('denied',views.denied , name='denied'),
    path('md-nt',views.data , name='md-nt'),


]

shakawi_manzoma/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shakawi.urls')),
    # path('accounts/', include('shakawi.urls')),
]



from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shakawi/models.py
from django.db import models
from datetime import date
# Create your models here.

class Shab(models.Model):
    shab_num = models.IntegerField()
    shab_year = models.IntegerField()
    shab_markaz = models.IntegerField()
    shab_mosalsal = models.IntegerField()
    shab_name = models.CharField(max_length = 255)
    shab_city = models.CharField(max_length = 64)
    medical_dec  =models.CharField(max_length = 64)
    note_type  =models.CharField(max_length = 64)
    shab_image = models.FileField(upload_to='shakawi_data/%Y/%m/%d')
    date_recored = models.DateField(default = date.today)
    rays = models.CharField(max_length = 64, default="")
    reports = models.CharField(max_length = 64, default="")


    def __str__(self):
        return self.shab_name + "  --->  الرقم الثلاثى : "+str(self.shab_year)+"-"+str(self.shab_markaz)+"-"+str(self.shab_mosalsal) + "    --  تاريخ التسجيل " + str(self.date_recored)







class Medical(models.Model):
    id = models.AutoField(primary_key = True)
    g_id = models.IntegerField(default=0)
    note = models.CharField(max_length=128)
    # name = models.CharField(max_length=50 , default="")

    def __str__(self):
        return self.note +" ------ ID -> " + str(self.g_id)
class Note_Type (models.Model):
    id = models.AutoField(primary_key = True)
    g_id = models.IntegerField(default=0)
    note  = models.CharField(max_length=128)

    def __str__(self):
        return self.note +" ------ ID ->" + str(self.g_id)

shakawi/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Shab,Note_Type,Medical
from datetime import datetime,date
from django.contrib.sessions.models import Session
# Create your views here.


def home(request):
   
    if request.method == 'POST':
        # print(request.POST)
        user_name = request.POST['user_name']
        password = request.POST['password']
        user = authenticate(request, username=user_name, password=password)
        if user is not None:
            failed =0
            login(request, user)
            # request.session.set_expiry(1)

            print('username: ' + request.user.username + ' has log in to system at ' + str(datetime.now()))

            if user.groups.filter(name='فرع الشكاوى').exists():
                #return redirect('taktet/')
                return shakawi_user(request)

            ## all general users have only one view page -> search for single persons data
            elif  user.groups.filter(name='مستخدم عام').exists():
                return general_user(request)

        else:
            failed =1
            context = {'failed' : failed,
                        'show':0,

                        }
            return render(request, 'shakawi/login.html', context = context)


    return render(request, 'shakawi/login.html',  context={'show':0} )

@login_required
def logout_view(request):
    logout(request)
    # print('username: ' + userna + ' has log out of system at ' + str(datetime.now()))

    return render(request, 'shakawi/login.html' , context={'show':0})





@login_required
@user_passes_test(lambda u: u.groups.filter(name='فرع الشكاوى').count() != 0, login_url='/denied')
def shakawi_user(request):

    return redirect('shakawi:new_shab_fit',0)



@login_required
@user_passes_test(lambda u: u.groups.all().count() != 0, login_url='/denied')
def general_user(request):
    # context = {'times':1}
    # return render(request, 'shakawi/search_single.html', context = context)
    return redirect('shakawi:search_single')

@login_required
@user_passes_test(lambda u: u.groups.filter(name='فرع الشكاوى').count() != 0, login_url='/denied')
def new_shab(request,page_id):

    ###########
    ##  page id
    ## 0.  new shab fit
    ## 1. new shab unfit
    ## 2. new shab ability
    ## 3. new shab 10%
    ##########


    if request.method == 'POST':
        rays = ""
        reports=""
        shab_name=""
        shab_year = request.POST['year']
        shab_markaz = request.POST['markaz']
        shab_mosalsal = request.POST['mosalsal']
        if 'name' in request.POST:
            shab_name = request.POST['name']
        shab_city = request.POST['city']

        medical_dec = request.POST['medical_dec']
        medical_dec = Medical.objects.get(g_id = int(medical_dec)).note

        note_type = request.POST['note_type']
        note_type = Note_Type.objects.get(g_id = int(note_type)).note

        shab_image = request.FILES['image']
        if 'rays' in request.POST:
            rays = request.POST['rays']
        if 'reports' in request.POST:
            reports = request.POST['reports']
        shab_data = Shab.objects.filter(shab_year  = shab_year, shab_markaz = shab_markaz, shab_mosalsal = shab_mosalsal , date_recored = date.today() )
        if (len(shab_data)) > 0:

            context ={
                'data' : shab_data.first(),

                'show':1,
                'error':1,
            }
            return render(request, 'shakawi/show_single.html',context)
        else:
            if page_id == 0: ## new shab fit
                shab_num = get_shab_num(date.today().year, note_type, shab_city,1)
                new_sh=Shab(shab_num = shab_num, shab_year=shab_year, shab_markaz= shab_markaz, shab_mosalsal = shab_mosalsal, shab_name = shab_name,
                                    shab_city = shab_city, medical_dec = medical_dec, note_type = note_type, shab_image = shab_image ,rays = rays, reports = reports)

                new_sh.save()


            elif page_id == 1: ## new shab unfit
                shab_num = get_shab_num(date.today(), note_type, shab_city,0)
                new_sh=Shab(shab_num = shab_num, shab_year=shab_year, shab_markaz= shab_markaz, shab_mosalsal = shab_mosalsal, shab_name = shab_name,
                                    shab_city = shab_city, medical_dec = medical_dec, note_type = note_type, shab_image = shab_image ,rays = rays, reports = reports)

                new_sh.save()


            elif page_id == 2: ## new shab ability
                    shab_num =0
                    new_sh=Shab(shab_num = shab_num, shab_year=shab_year, shab_markaz= shab_markaz, shab_mosalsal = shab_mosalsal, shab_name = shab_name,
                                        shab_city = shab_city, medical_dec = medical_dec, note_type = note_type, shab_image = shab_image ,rays = rays, reports = reports)

                    new_sh.save()


            elif page_id == 3:## new shab 10%
                shab_num =0
                new_sh=Shab(shab_num = shab_num, shab_year=shab_year, shab_markaz= shab_markaz, shab_mosalsal = shab_mosalsal, shab_name = shab_name,
                                    shab_city = shab_city, medical_dec = medical_dec, note_type = note_type, shab_image = shab_image ,rays = rays, reports = reports)

                new_sh.save()

    total,medicals,notes = get_total_notes_medicals(int(page_id))

    context = {

                 'show':1,
                'sh_72':get_arabic_date(total),
                'notes' : notes,
                'medicals' : medicals,

                }
    if page_id==0 :## new shab fit
        return render(request, 'shakawi/new_shab_fit.html', context = context)
    elif page_id==1 :## new shab unfit
        return render(request, 'shakawi/new_shab_unfit.html', context = context)

    elif page_id==2 :## new shab ability
        return render(request, 'shakawi/new_shab_ability.html', context = context)

    elif page_id==3 :## new shab 10%
        return render(request, 'shakawi/new_shab_ten.html', context = context)




def get_total_notes_medicals(page_id):
    total = medical = notes = 0
    n_names = []
    if page_id ==0:## new shab fit
        notes = Note_Type.objects.filter(g_id__in=[1,2,6])
        medical = Medical.objects.filter(g_id__in=[1,2])
        n_names.extend([notes[0].note,notes[1].note,notes[2].note])
        total = len(Shab.objects.filter(date_recored = date.today(), note_type__in=n_names))
        if Shab.objects.filter(date_recored = date.today(), note_type__in=n_names) :
            print(date.today())
    elif page_id ==1:## new shab unfit
        notes = Note_Type.objects.filter(g_id__in=[3])
        medical = Medical.objects.filter(g_id__in=[3])
        n_names.extend([notes[0].note])
        total = len(Shab.objects.filter(date_recored = date.today(), note_type__in=n_names))
    elif page_id ==2:## new shab ability
        notes = Note_Type.objects.filter(g_id__in=[4])
        medical = Medical.objects.filter(g_id__in=[4,5])
        n_names.extend([notes[0].note])
        total = len(Shab.objects.filter(date_recored = date.today(), note_type__in=n_names))
    elif page_id ==3:## new shab 10%
        notes = Note_Type.objects.filter(g_id__in=[5])
        medical = Medical.objects.filter(g_id__in=[6,7])
        n_names.extend([notes[0].note])
        total = len(Shab.objects.filter(date_recored = date.today(), note_type__in=n_names))


    return (total,medical,notes)


###########################################
# get each new shab id based on there filters
#1. city
#2. note_type
#3. year of date_recored
#4. status 1. continous counting from start to the end of the year
#   status 0 . count day by day
#################################################
def get_shab_num(year_rec, note_type, city, status):
    shab_num = 1

    if status == 1 :
        shab_num = len(Shab.objects.filter(date_recored__year = year_rec, note_type = note_type, shab_city = city)) +1
    elif status ==0:
        shab_num = len(Shab.objects.filter(date_recored = year_rec, note_type = note_type, shab_city = city)) +1



    return shab_num



###############################################################################
#
#\ all users  views
################################################################################

@login_required
@user_passes_test(lambda u: u.groups.all().count() != 0, login_url='/denied')
def search_single(request):
    if request.method == "POST":
        year = request.POST['year']
        markaz = request.POST['markaz']
        mosalsal = request.POST['mosalsal']
        shab_data = Shab.objects.filter(shab_year = year, shab_markaz = markaz, shab_mosalsal = mosalsal).last()
        # date = get_arabic_date(shab_data.date_recored)
        # shab_data.date_recored = date
        context ={
            'data' : shab_data,

            'show':1,
        }
        return render(request, 'shakawi/show_single.html',context)
    else:
        context = {

                    'show':1,
                    }
        return render(request, 'shakawi/search_single.html',  context = context)


from django.utils.translation import gettext as _

@login_required
@user_passes_test( lambda u :u.groups.filter(name='فرع الشكاوى').count() != 0 , login_url='/denied')
def print_reports(request):

    if request.method == "POST":
        search_date = request.POST['date_recored']
        if not search_date:
            search_date = date.today()
        city = request.POST['city']
        note_type = int(request.POST['note_type'])
        note_type = Note_Type.objects.get(g_id = note_type).note

        data = Shab.objects.filter(shab_city = city, note_type = note_type , date_recored = search_date).order_by('shab_num')
        print("data found # %d"%(len(data)))
        search_date = get_arabic_date(search_date)
        context = {

shakawi/templates/shakawi/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static   'shakawi/style.css' %}?ver=1.1">
    <!-- <link rel="stylesheet" href="{% static 'shakawi/bootstrap-4.3.1-dist/css/bootstrap.min.css' %}" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->

</head>
<body>
  
    {% block content %}
    {% endblock %}
    
    <script src="{% static   'shakawi/jquery.js' %}"></script>

    <script>
        $(function(){
            //to convert arabic numbers to persian numbers
            var arabicNumbers = ['۰', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];
            var convert_to_persian_numbers = function (v) {
                var chars = v.split('');
                for (var i = 0; i < chars.length; i++) {
                    if (/\d/.test(chars[i])) {
                    chars[i] = arabicNumbers[chars[i]];
                    }
                }
                return chars.join('');
            }

            //to write down the date

            var today_d = new Date();
            var d = today_d.getDate();
            var m = today_d.getMonth()+1;
            var y = today_d.getFullYear();
            today = d +" / "+m +" / "+y +" "
            $('.today-date').text(': ' + convert_to_persian_numbers(today));



        });

    </script>
    <!-- <script src="{% static 'shakawi/bootstrap-4.3.1-dist/js/bootstrap.min.js' %}" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->

</body>
</html>

shakawi/templates/shakawi/denied.html
{% extends './base.html' %}
{% block content %}

    {% include './header.html' with title='مكتب الشكاوي الطبية' %}
    <div id="inquire-2-page" class="page">
        <div id="inquire-2-square">
            <h3 style="font-size: 1.5em; color:red;">عفواً لاتملك الصلاحيات للوصول لهذا المحتوى</h3>
        </div>
    </div>
{% endblock %}

shakawi/templates/shakawi/depts_users.html
{% extends './base.html' %}
{% block content %}

    {% include './header.html' with title='مكتب الشكاوي الطبية' %}

    <div  class="container"  id="reports-page" dir="rtl">
        <br><br>
      <div class="" id="post-square">
        <h1> القرار الطبى</h1>
        <table >
        <head>
          <th> القرار </th>
          <th> ID </th>

        </head>
        {%for med in medicals%}

          <tr  >


            <td>{{med.note}}</td>
            <td>{{med.g_id}}</td>

          </tr>

          {%endfor%}
        </table>
      </div>
      <br><br>
    <div class="" id="post-square">
      <h1>نوع المذكرة</h1>
      <table>
      <head>
        <th>المذكرة</th>
        <th> ID </th>

      </head>
        {%for note in notes%}
        <tr>
          <td>{{note.note}}</td>
          <td>{{note.g_id}}</td>
        </tr>

        {%endfor %}
      </table>
    </div>

    </div>


{% endblock %}

shakawi/templates/shakawi/header.html
{%load static%}
<header>
    <div>
        <div>هيئة التنظيم و الإدارة</div>
        <div>إدارة التجنيد و التعبئة</div>
        <div>منطقة تجنيد و تعبئة الزقازيق</div>
        <div>
            <span>التاريخ</span>
            <span class="today-date translate"></span>
        </div>
    </div>
    <div class="title"><h1>{{ title }}</h1></div>
    <div id="logo_div">
        <img src="{%static 'shakawi/background.png' %}" alt="logo" height="125px" width="150px">
    </div>

</header>
  {% if  user.is_authenticated and show %}
<br>

<div class="topnav" >
    <nav>

      <a href="{%url 'shakawi:new_shab_fit' page_id=0 %}" class="btn">صفحة تسجيل اللائق</a>
      <a href="{%url 'shakawi:new_shab_unfit' page_id=1 %}" class="btn">صفحة تسجيل الغير لائق</a>
      <a href="{%url 'shakawi:new_shab_ability' page_id=2 %}" class="btn">صفحة تسجيل القدرة</a>
      <a href="{%url 'shakawi:new_shab_ten' page_id=3 %}" class="btn">صفحة تسجيل ال 10%</a>

      <a href="{%url 'shakawi:search_reports'%}"  class="btn">طباعة التقارير</a>
      <a href="{%url 'shakawi:search_single'%}"  class="btn">صفحة الاستعلام</a>
      <a href="{%url 'shakawi:logout'%}"  class="btn">تسجيل الخروج</a>


    </nav>
    
</div>

  {% endif %}

shakawi/templates/shakawi/login.html
{% extends './base.html' %}
{% block content %}

    {% include './header.html' with title='مكتب الشكاوي الطبية'%}
    <div id="login-page" class="page">
        <div id="login-square">
            <form action="" method="post">
                {%csrf_token %}
                <div class="login-form-field">
                    <input type="text" name="user_name" id="username" placeholder="اسم المستخدم"  required>
                </div>
                <div class="login-form-field">
                    <input type="password" name="password" id="password" placeholder="كلمة المرور" required>
                </div>
                <div class="login-form-field">
                    <button class="btn btn-login" type="submit">تسجيـــل الدخــــول</button>
                </div>
            </form>
            {% if failed %}
            <div class="login-form-field error" >
                <p class"error">خطأ فى كلمة السر او إسم المستخدم</p>
            </div>
            {%endif%}
        </div>
    </div>
{% endblock %}

shakawi/templates/shakawi/main.html
{% extends './base.html' %}
{% block content %}

    {% include './header.html' with title='مكتب الشكاوي الطبية' %}
    <div id="nav-page" class="page">
        <div id="nav-square">
            <div class="login-form-field">
                <div class="">
                  <a href="{%url 'shakawi:new_shab_fit' page_id=0 %}" class="btn">صفحة تسجيل اللائق</a>
                  <a href="{%url 'shakawi:new_shab_fit' page_id=0 %}" class="btn">صفحة تسجيل الغير لائق</a>
                </div>
                <br><br>
                <div class="">
                  <a href="{%url 'shakawi:new_shab_fit' page_id=0 %}" class="btn">صفحة تسجيل القدرة</a>
                  <a href="{%url 'shakawi:new_shab_fit' page_id=0 %}" class="btn">صفحة تسجيل ال 10%</a>
                </div>
                <br><br>
                <div class="">
                  <a href="{%url 'shakawi:search_single'%}"  class="btn">صفحة الاستعلام</a>
                  <a href="{%url 'shakawi:search_reports'%}"  class="btn">طباعة التقارير</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

shakawi/templates/shakawi/new_shab_ability.html
{% extends './base.html' %}
{% block content %}


    {% include './header.html' with title='شاشة التسجيل كشف القدرة' %}
    <
    <div class="daily-div  page  " id="inquire-square">

        <div style="display:block; margin-bottom: 5px;">
            <h2> إجمالى ما تم تسجيله اليوم
            <span class="today-date translate"></span> </h2>
        </div>
        <hr>
        <div class="daily-box" style="text-align: center;">
            <label for=""><h1 >{{sh_72}} شاب</h1></label>

        </div>



    </div>
    <div id="post-page" class="page">
        <div id="post-square">
            <form id="post-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="ability-div">
                        <input type="number"  min="1900" size="4" maxlength="4" placeholder="السنة" name="year" class="translate"  required>
                        <input type="number"  min="1" size="3" maxlength="3" placeholder="المركز" name="markaz"  required>
                        <input type="number" min="1" size="5" placeholder="المسلسل"  name="mosalsal"   required>
                        </div>
                        <div class="ability-div">

                                                  <select name="city" id=""  required>
                                                      <option>المحافظة</option>
                                                      <option value="الشرقية" selected>الشرقية</option>
                                                      <option value="القنال">القنال</option>
                                                  </select>

                                                  <select name="medical_dec" id=""  required>
                                                      <option>القرار الطبي</option>
                                                      {%for med in medicals%}
                                                          {%if forloop.counter == 1%}
                                                            <option value="{{med.g_id}}" selected>{{med.note}}</option>

                                                          {%else%}
                                                            <option value="{{med.g_id}}">{{med.note}}</option>
                                                          {%endif%}
                                                      {%endfor%}

                                                  </select>

                                                  <select name="note_type" id="" required>
                                                      <option>نوع المذكرة</option>
                                                      {%for note in notes %}
                                                          {%if forloop.counter == 1%}
                                                            <option value="{{note.g_id}}" selected>{{note.note}}</option>

                                                          {%else%}
                                                            <option value="{{note.g_id}}">{{note.note}}</option>
                                                          {%endif%}
                                                      {%endfor%}
                                                    
                                                  </select>
                        </div>
                      <div class="ability-div">
                        <div class="file-container" >
                            <input type="file" name='image' required>
                        </div>

                        <button class="btn" type="submit">حفظ</button>
                    </div>
                </form>
                </div>

        </div>


{% endblock %}

shakawi/templates/shakawi/new_shab_fit.html
{% extends './base.html' %}
{% block content %}


    {% include './header.html' with title='شاشة التسجيل اللائق طبيا' %}
    <div class="daily-div  page  " id="inquire-square">

        <div style="display:block; margin-bottom: 5px;">
            <h2> إجمالى ما تم تسجيله اليوم
            <span class="today-date translate"></span> </h2>
        </div>
        <hr>
        <div class="daily-box" style="text-align: center;">
            <label for=""><h1 >{{sh_72}} شاب</h1></label>

        </div>



    </div>
    <div id="post-page" class="page">
        <div id="post-square">
            <form id="post-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <div>
                        <input type="number"  min="1900" size="4" maxlength="4" placeholder="السنة" name="year" class="translate"  required>
                        <input type="number"  min="1" size="3" maxlength="3" placeholder="المركز" name="markaz"  required>
                        <input type="number" min="1" size="5" placeholder="المسلسل"  name="mosalsal"   required>

                        <input type="text" placeholder="الإسم" name="name"  required>

                        <select name="city" id=""  required>
                            <option>المحافظة</option>
                            <option value="الشرقية" selected>الشرقية</option>
                            <option value="القنال">القنال</option>
                        </select>

                        <select name="medical_dec" id=""  required>
                            <option>القرار الطبي</option>
                            {%for med in medicals%}
                                {%if forloop.counter == 1%}
                                  <option value="{{med.g_id}}" selected>{{med.note}}</option>

                                {%else%}
                                  <option value="{{med.g_id}}">{{med.note}}</option>
                                {%endif%}
                            {%endfor%}

                        </select>

                        <select name="note_type" id="" required>
                            <option>نوع المذكرة</option>
                            {%for note in notes %}
                                {%if forloop.counter == 1%}
                                  <option value="{{note.g_id}}" selected>{{note.note}}</option>

                                {%else%}
                                  <option value="{{note.g_id}}">{{note.note}}</option>
                                {%endif%}
                            {%endfor%}
                            
                        </select>
                            <div  class="checkbox-wrapper">
                                <label  for="ra"  >اشعة</label>
                                <input  type="checkbox" value="اشعة" id="ra" name="rays" >

                            </div>
                            <div    class="checkbox-wrapper">
                                <label  for="re">ابحاث</label>
                                <input type="checkbox" value="ابحاث" id="re" name="reports" >

                            </div>


                        <div class="file-container" >
                            <input type="file" name='image' required>
                        </div>

                        <button class="btn" type="submit">حفظ</button>
                    </div>
                </form>
                </div>

        </div>


{% endblock %}

shakawi/templates/shakawi/new_shab_ten.html
{% extends './base.html' %}
{% block content %}


    {% include './header.html' with title='شاشة التسجيل ال 10 %' %}
    <div class="daily-div  page  " id="inquire-square">

        <div style="display:block; margin-bottom: 5px;">
            <h2> إجمالى ما تم تسجيله اليوم
            <span class="today-date translate"></span> </h2>
        </div>
        <hr>
        <div class="daily-box" style="text-align: center;">
            <label for=""><h1 >{{sh_72}} شاب</h1></label>

        </div>



    </div>
    <div id="post-page" class="page">
        <div id="post-square">
            <form id="post-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="ability-div">
                    <input type="number"  min="1900" size="4" maxlength="4" placeholder="السنة" name="year" class="translate"  required>
                    <input type="number"  min="1" size="3" maxlength="3" placeholder="المركز" name="markaz"  required>
                    <input type="number" min="1" size="5" placeholder="المسلسل"  name="mosalsal"   required>
                    </div>
                    <div class="ability-div">

                                              <select name="city" id=""  required>
                                                  <option>المحافظة</option>
                                                  <option value="الشرقية" selected>الشرقية</option>
                                                  <option value="القنال">القنال</option>
                                              </select>

                                              <select name="medical_dec" id=""  required>
                                                  <option>القرار الطبي</option>
                                                  {%for med in medicals%}
                                                      {%if forloop.counter == 1%}
                                                        <option value="{{med.g_id}}" selected>{{med.note}}</option>

                                                      {%else%}
                                                        <option value="{{med.g_id}}">{{med.note}}</option>
                                                      {%endif%}
                                                  {%endfor%}

                                              </select>

                                              <select name="note_type" id="" required>
                                                  <option>نوع المذكرة</option>
                                                  {%for note in notes %}
                                                      {%if forloop.counter == 1%}
                                                        <option value="{{note.g_id}}" selected>{{note.note}}</option>

                                                      {%else%}
                                                        <option value="{{note.g_id}}">{{note.note}}</option>
                                                      {%endif%}
                                                  {%endfor%}

                                              </select>
                    </div>
                  <div class="ability-div">
                    <div class="file-container" >
                        <input type="file" name='image' required>
                    </div>

                    <button class="btn" type="submit">حفظ</button>
                </div>
            </form>
            </div>

    </div>


{% endblock %}

shakawi/templates/shakawi/search_reports.html
{% extends './base.html' %}
{% block content %}


    {% include './header.html' with title='شاشة طباعة التقارير' %}
    <div id="search-report-page" class="page">
        <div id="search-report-square">
            <form id="search-report-form" method="post">
                {% csrf_token %}
                    <div>
                        <input type="date" size="4"  placeholder="التاريخ" name="date_recored" required>

                        <select name="city" id=""  required>
                            <option>المحافظة</option>
                            <option value="الشرقية" >الشرقية</option>
                            <option value="القنال">القنال</option>
                        </select>

                        <select name="note_type" id="" required>
                            <option>نوع المذكرة</option>
                            {%for note in notes %}
                                <option value="{{note.g_id}}">{{note.note}}</option>
                            {%endfor%}

                        </select>
                        <button class="btn" type="submit">البحث عن التقرير</button>
                    </div>
            </form>
        </div>
    </div>

{% endblock %}